== Core Operators

=== Logical Operator (6)

Boolean connectives, evaluated with three-valued (true/false/null) logic.

Members: xref:cql-dictionary.html#term-and[`and`], xref:cql-dictionary.html#term-exists[`exists`], xref:cql-dictionary.html#term-implies[`implies`], xref:cql-dictionary.html#term-not[`not`], xref:cql-dictionary.html#term-or[`or`], xref:cql-dictionary.html#term-xor[`xor`]

=== Arithmetic Operator (6)

Numeric operators beyond the basic +, -, *, /.

Members: xref:cql-dictionary.html#term-div[`div`], xref:cql-dictionary.html#term-maximum[`maximum`], xref:cql-dictionary.html#term-minimum[`minimum`], xref:cql-dictionary.html#term-mod[`mod`], xref:cql-dictionary.html#term-predecessor[`predecessor`], xref:cql-dictionary.html#term-successor[`successor`]

=== Type Operator (5)

Casting and type-checking between CQL's types.

Members: xref:cql-dictionary.html#term-as[`as`], xref:cql-dictionary.html#term-cast[`cast`], xref:cql-dictionary.html#term-convert[`convert`], xref:cql-dictionary.html#term-is[`is`], xref:cql-dictionary.html#term-to[`to`]

=== Comparison Operator (1)

General-purpose range comparison.

Members: xref:cql-dictionary.html#term-between[`between`]
