:chapter-id: data-and-timing-operators
:chapter-parent: cql
:chapter-order: 700
:chapter-status: published

= Data & Timing Operators

== List/Interval Operator (17)

Operators for combining, comparing, and inspecting lists and intervals.

Members: xref:cql-dictionary.html#term-collapse[`collapse`], xref:cql-dictionary.html#term-contains[`contains`], xref:cql-dictionary.html#term-distinct[`distinct`], xref:cql-dictionary.html#term-end[`end`], xref:cql-dictionary.html#term-except[`except`], xref:cql-dictionary.html#term-expand[`expand`], xref:cql-dictionary.html#term-flatten[`flatten`], xref:cql-dictionary.html#term-in[`in`], xref:cql-dictionary.html#term-included-in[`included in`], xref:cql-dictionary.html#term-includes[`includes`], xref:cql-dictionary.html#term-intersect[`intersect`], xref:cql-dictionary.html#term-point[`point`], xref:cql-dictionary.html#term-properly[`properly`], xref:cql-dictionary.html#term-singleton[`singleton`], xref:cql-dictionary.html#term-start[`start`], xref:cql-dictionary.html#term-union[`union`], xref:cql-dictionary.html#term-width[`width`]

== Timing Operator (17)

Allen's-interval-algebra-style relationships between dates, times, and intervals.

Members: xref:cql-dictionary.html#term-after[`after`], xref:cql-dictionary.html#term-before[`before`], xref:cql-dictionary.html#term-during[`during`], xref:cql-dictionary.html#term-ends[`ends`], xref:cql-dictionary.html#term-meets[`meets`], xref:cql-dictionary.html#term-occurs[`occurs`], xref:cql-dictionary.html#term-on[`on`], xref:cql-dictionary.html#term-or-after[`or after`], xref:cql-dictionary.html#term-or-before[`or before`], xref:cql-dictionary.html#term-or-less[`or less`], xref:cql-dictionary.html#term-or-more[`or more`], xref:cql-dictionary.html#term-or-on[`or on`], xref:cql-dictionary.html#term-overlaps[`overlaps`], xref:cql-dictionary.html#term-per[`per`], xref:cql-dictionary.html#term-same[`same`], xref:cql-dictionary.html#term-starts[`starts`], xref:cql-dictionary.html#term-within[`within`]

== Time-Precision Unit (16)

The calendar-duration units quantities and date arithmetic are expressed in.

Members: xref:cql-dictionary.html#term-day[`day`], xref:cql-dictionary.html#term-days[`days`], xref:cql-dictionary.html#term-hour[`hour`], xref:cql-dictionary.html#term-hours[`hours`], xref:cql-dictionary.html#term-millisecond[`millisecond`], xref:cql-dictionary.html#term-milliseconds[`milliseconds`], xref:cql-dictionary.html#term-minute[`minute`], xref:cql-dictionary.html#term-minutes[`minutes`], xref:cql-dictionary.html#term-month[`month`], xref:cql-dictionary.html#term-months[`months`], xref:cql-dictionary.html#term-second[`second`], xref:cql-dictionary.html#term-seconds[`seconds`], xref:cql-dictionary.html#term-week[`week`], xref:cql-dictionary.html#term-weeks[`weeks`], xref:cql-dictionary.html#term-year[`year`], xref:cql-dictionary.html#term-years[`years`]

== Extraction Operator (6)

Pulling a component (date, time, precision) out of a date/time value.

Members: xref:cql-dictionary.html#term-date[`date`], xref:cql-dictionary.html#term-difference[`difference`], xref:cql-dictionary.html#term-duration[`duration`], xref:cql-dictionary.html#term-of[`of`], xref:cql-dictionary.html#term-time[`time`], xref:cql-dictionary.html#term-timezoneoffset[`timezoneoffset`]
