:chapter-id: query-and-control-flow
:chapter-parent: cql
:chapter-order: 800
:chapter-status: published

= Query & Control Flow

== Query Clause (12)

The clauses that make up a CQL query: source, filter, relate, shape, sort.

Members: xref:cql-dictionary.html#term-aggregate[`aggregate`], xref:cql-dictionary.html#term-all[`all`], xref:cql-dictionary.html#term-by[`by`], xref:cql-dictionary.html#term-from[`from`], xref:cql-dictionary.html#term-let[`let`], xref:cql-dictionary.html#term-return[`return`], xref:cql-dictionary.html#term-sort[`sort`], xref:cql-dictionary.html#term-starting[`starting`], xref:cql-dictionary.html#term-such-that[`such that`], xref:cql-dictionary.html#term-where[`where`], xref:cql-dictionary.html#term-with[`with`], xref:cql-dictionary.html#term-without[`without`]

== Conditional Expression (5)

Branching logic -- choose a result based on a condition.

Members: xref:cql-dictionary.html#term-case[`case`], xref:cql-dictionary.html#term-else[`else`], xref:cql-dictionary.html#term-if[`if`], xref:cql-dictionary.html#term-then[`then`], xref:cql-dictionary.html#term-when[`when`]

== Sort Modifier (4)

Direction keywords for the sort clause.

Members: xref:cql-dictionary.html#term-asc[`asc`], xref:cql-dictionary.html#term-ascending[`ascending`], xref:cql-dictionary.html#term-desc[`desc`], xref:cql-dictionary.html#term-descending[`descending`]

[TIP]
====
For the complete alphabetical reference of all 122 CQL keywords, including formal syntax, typing rules, and clinical examples, see the standalone xref:cql-dictionary.html[CQL Keyword Dictionary].
====
